apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: njila

bases:
  - ../../base

# En production : 2+ réplicas pour la haute disponibilité
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      labelSelector: "tier=microservice"
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      labelSelector: "tier=gateway"

configMapGenerator:
  - name: prod-config
    namespace: njila
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=WARN
