# Generated by Django 5.2.12 on 2026-03-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='njilauser',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='njilauser',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='njilauser',
            name='agence_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='njilauser',
            index=models.Index(fields=['agence_id', 'is_active'], name='auth_users_agence_active_idx'),
        ),
        migrations.AddIndex(
            model_name='njilauser',
            index=models.Index(fields=['agence_id', 'role'], name='auth_users_agence_role_idx'),
        ),
    ]
