# Generated by Django 5.2.12 on 2026-03-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_njilauser_deactivation_reason_njilauser_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='njilauser',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='njilauser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='njilauser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='njilauser',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
