# Generated by Django 5.2.12 on 2026-04-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_njilauser_adresse_njilauser_name_njilauser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='njilauser',
            name='photo_url',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
