# Generated by Django 5.2.12 on 2026-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_njilauser_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='njilauser',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
