# Generated by Django 5.2.12 on 2026-04-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_njilauser_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='njilauser',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
