# ─── Application ──────────────────────────────────────────────────────────────
spring.application.name=njila-proxy-service

# ─── Configuration Server ─────────────────────────────────────────────────────
spring.cloud.config.uri=http://njila-conf-service:8080
spring.config.import=configserver:
