# Generated by Django 5.2.12 on 2026-03-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenceMere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agence_id', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True, default='')),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('email_officiel', models.EmailField(max_length=254, unique=True)),
                ('statut_global', models.CharField(default='EN_ATTENTE', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('logo_image', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'db_table': 'agences',
            },
        ),
    ]
