# Generated by Django 4.2.29 on 2026-03-26 01:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id_agence', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email_officiel', models.EmailField(max_length=254, unique=True)),
                ('statut_global', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('expiree', 'Expirée'), ('en_attente', 'En attente')], default='active', max_length=20)),
                ('logo_image', models.URLField(blank=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'db_table': 'njila_agence',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('IdBus', models.AutoField(primary_key=True, serialize=False)),
                ('modele', models.CharField(max_length=50)),
                ('immatriculation', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\s]+$', "L'immatriculation ne doit contenir que des lettres majuscules et des chiffres")])),
                ('capacite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('en_panne', 'En panne'), ('en_voyage', 'En voyage'), ('maintenance', 'En maintenance'), ('reserve', 'Réservé')], default='disponible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Id_agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='fleet.agence')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Bus',
                'db_table': 'njila_bus',
            },
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id_chauffeur', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_permis', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('Adresse', models.TextField()),
                ('photo_profil', models.URLField(blank=True)),
                ('est_disponible', models.BooleanField(default=True)),
                ('date_embauche', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Id_agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chauffeurs', to='fleet.agence')),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
                'db_table': 'njila_chauffeur',
            },
        ),
        migrations.CreateModel(
            name='Filiale',
            fields=[
                ('id_filiale', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('ville', models.CharField(choices=[('Douala', 'Douala'), ('Yaoundé', 'Yaoundé'), ('Bafoussam', 'Bafoussam'), ('Garoua', 'Garoua'), ('Ngaoundéré', 'Ngaoundéré'), ('Bamenda', 'Bamenda'), ('Maroua', 'Maroua'), ('Kribi', 'Kribi'), ('Limbe', 'Limbe'), ('Ebolowa', 'Ebolowa')], max_length=50)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('est_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiales', to='fleet.agence')),
            ],
            options={
                'verbose_name': 'Filiale',
                'verbose_name_plural': 'Filiales',
                'db_table': 'njila_filiale',
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('Id_trajet', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance', models.FloatField(help_text='Distance en kilomètres', validators=[django.core.validators.MinValueValidator(0)])),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filiale_arrive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trajets_arrivee', to='fleet.filiale')),
                ('filiale_depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trajets_depart', to='fleet.filiale')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
                'db_table': 'njila_trajet',
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('Id_voyage', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_heure_depart', models.DateTimeField()),
                ('date_heure_arrive_prevue', models.DateTimeField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_voyage', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('confort', 'Confort'), ('luxe', 'Luxe')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('programme', 'Programmé'), ('confirme', 'Confirmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('retarde', 'Retardé')], default='programme', max_length=20)),
                ('places_disponibles', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('places_total_reservees', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_heure_arrive_reelle', models.DateTimeField(blank=True, null=True)),
                ('motif_annulation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('IdBus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='fleet.bus')),
                ('Id_trajet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='fleet.trajet')),
                ('id_chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages', to='fleet.chauffeur')),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Voyages',
                'db_table': 'njila_voyage',
            },
        ),
        migrations.CreateModel(
            name='Guichetier',
            fields=[
                ('Id_guichetier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('adresse', models.TextField()),
                ('photo_profil', models.URLField(blank=True)),
                ('password', models.CharField(max_length=255)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_id_filiale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guichetiers', to='fleet.filiale')),
            ],
            options={
                'verbose_name': 'Guichetier',
                'verbose_name_plural': 'Guichetiers',
                'db_table': 'njila_guichetier',
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id_avis', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date_avis', models.DateTimeField(auto_now_add=True)),
                ('commentaires', models.TextField()),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('est_approuve', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Id_voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='fleet.voyage')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'db_table': 'njila_avis',
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id_annonce', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('retard', 'Retard'), ('annulation', 'Annulation'), ('promotion', 'Promotion'), ('information', 'Information')], max_length=20)),
                ('message', models.TextField()),
                ('datePublication', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Id_voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='fleet.voyage')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'db_table': 'njila_annonce',
            },
        ),
        migrations.AddIndex(
            model_name='agence',
            index=models.Index(fields=['statut_global'], name='njila_agenc_statut__c72c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='agence',
            index=models.Index(fields=['email_officiel'], name='njila_agenc_email_o_a791ca_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['status'], name='njila_voyag_status_1211d5_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['date_heure_depart'], name='njila_voyag_date_he_e1fb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['Id_trajet', 'date_heure_depart'], name='njila_voyag_Id_traj_d828d0_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['IdBus', 'status'], name='njila_voyag_IdBus_i_f78821_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['id_chauffeur'], name='njila_voyag_id_chau_2b7801_idx'),
        ),
        migrations.AddIndex(
            model_name='trajet',
            index=models.Index(fields=['filiale_depart', 'filiale_arrive'], name='njila_traje_filiale_772156_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trajet',
            unique_together={('filiale_depart', 'filiale_arrive')},
        ),
        migrations.AddIndex(
            model_name='guichetier',
            index=models.Index(fields=['email'], name='njila_guich_email_71c462_idx'),
        ),
        migrations.AddIndex(
            model_name='guichetier',
            index=models.Index(fields=['_id_filiale'], name='njila_guich__id_fil_e038ab_idx'),
        ),
        migrations.AddIndex(
            model_name='filiale',
            index=models.Index(fields=['code'], name='njila_filia_code_6a36e1_idx'),
        ),
        migrations.AddIndex(
            model_name='filiale',
            index=models.Index(fields=['ville', 'est_active'], name='njila_filia_ville_6aec82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filiale',
            unique_together={('agence', 'code')},
        ),
        migrations.AddIndex(
            model_name='chauffeur',
            index=models.Index(fields=['numero_permis'], name='njila_chauf_numero__14d98c_idx'),
        ),
        migrations.AddIndex(
            model_name='chauffeur',
            index=models.Index(fields=['Id_agence'], name='njila_chauf_Id_agen_75f359_idx'),
        ),
        migrations.AddIndex(
            model_name='chauffeur',
            index=models.Index(fields=['est_disponible'], name='njila_chauf_est_dis_57a180_idx'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['immatriculation'], name='njila_bus_immatri_1481b2_idx'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['etat'], name='njila_bus_etat_1ba0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['Id_agence', 'etat'], name='njila_bus_Id_agen_42bdf1_idx'),
        ),
        migrations.AddIndex(
            model_name='avis',
            index=models.Index(fields=['Id_voyage'], name='njila_avis_Id_voya_d2cede_idx'),
        ),
        migrations.AddIndex(
            model_name='avis',
            index=models.Index(fields=['note'], name='njila_avis_note_db9a01_idx'),
        ),
        migrations.AddIndex(
            model_name='avis',
            index=models.Index(fields=['user_id'], name='njila_avis_user_id_fe1e3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('user_id', 'Id_voyage')},
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['Id_voyage'], name='njila_annon_Id_voya_33dc50_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['datePublication'], name='njila_annon_datePub_75068b_idx'),
        ),
    ]
