# Generated by Django 4.2.29 on 2026-03-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='logo_image',
            field=models.ImageField(blank=True, help_text="Logo de l'agence (format: JPG, PNG, max 2MB)", null=True, upload_to='agences/logos/'),
        ),
    ]
