# Generated by Django 4.2.29 on 2026-03-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_agence_logo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='date_heure_arrive_reelle',
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='photo_profil',
            field=models.ImageField(blank=True, help_text='Photo de profil du chauffeur (format: JPG, PNG, max 2MB)', null=True, upload_to='chauffeurs/photos/'),
        ),
        migrations.AlterField(
            model_name='filiale',
            name='ville',
            field=models.CharField(choices=[('Douala', 'Douala'), ('Yaoundé', 'Yaoundé'), ('Bafoussam', 'Bafoussam'), ('Garoua', 'Garoua'), ('Ngaoundéré', 'Ngaoundéré'), ('Bamenda', 'Bamenda'), ('Maroua', 'Maroua'), ('Kribi', 'Kribi'), ('Limbe', 'Limbe'), ('Ebolowa', 'Ebolowa'), ('Dschang', 'Dschang')], max_length=50),
        ),
        migrations.AlterField(
            model_name='guichetier',
            name='photo_profil',
            field=models.ImageField(blank=True, help_text='Photo de profil (format: JPG, PNG, max 2MB)', null=True, upload_to='guichetiers/photos/'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='type_voyage',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP')], default='standard', max_length=20),
        ),
    ]
