# Generated by Django 5.2.12 on 2026-03-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_agence', models.CharField(max_length=100)),
                ('plan', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel'), ('ESSAI', 'Essai')], max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_expiration', models.DateTimeField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TRIAL', 'Essai'), ('ACTIVE', 'Actif'), ('EXPIRING', 'Expirant'), ('EXPIRED', 'Expiré'), ('SUSPENDED', 'Suspendu'), ('RESILIATION', 'Résilié')], default='EN_ATTENTE', max_length=20)),
                ('cle_activation_hash', models.TextField(blank=True, default='')),
                ('id_transaction_paiement', models.CharField(blank=True, default='', max_length=255)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='agencies.agencemere')),
            ],
            options={
                'db_table': 'abonnements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='AlerteExpiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(max_length=10)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut_envoi', models.CharField(default='ENVOYE', max_length=20)),
                ('jours_restants', models.IntegerField(default=0)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='subscriptions.abonnement')),
            ],
            options={
                'db_table': 'alertes_expiration',
            },
        ),
        migrations.CreateModel(
            name='CleActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_chiffree', models.TextField()),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('revoquee', models.BooleanField(default=False)),
                ('nonce', models.CharField(max_length=64)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cles_activation', to='subscriptions.abonnement')),
            ],
            options={
                'db_table': 'cles_activation',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_agence', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('SOUSCRIPTION', 'Souscription'), ('RENOUVELLEMENT', 'Renouvellement'), ('SUSPENSION', 'Suspension'), ('REACTIVATION', 'Réactivation'), ('EXPIRATION', 'Expiration'), ('RESILIATION', 'Résiliation')], max_length=30)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, default='')),
                ('id_operateur', models.CharField(default='SYSTEM', max_length=100)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='subscriptions.abonnement')),
            ],
            options={
                'db_table': 'historique_abonnements',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_publique', models.TextField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('abonnement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_key', to='subscriptions.abonnement')),
            ],
            options={
                'db_table': 'subscription_keys',
            },
        ),
        migrations.CreateModel(
            name='ModuleAutorise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_module', models.CharField(choices=[('BOOKING', 'Réservations'), ('SEARCH', 'Recherche'), ('FLEET', 'Flotte'), ('NOTIFICATION', 'Notifications'), ('REPORTING', 'Rapports')], max_length=30)),
                ('actif', models.BooleanField(default=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='subscriptions.abonnement')),
            ],
            options={
                'db_table': 'modules_autorises',
                'unique_together': {('abonnement', 'nom_module')},
            },
        ),
    ]
