# Generated by Django 5.2.12 on 2026-04-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleautorise',
            name='nom_module',
            field=models.CharField(choices=[('BOOKING', 'Réservations'), ('FLEET', 'Flotte'), ('NOTIFICATION', 'Notifications')], max_length=30),
        ),
    ]
