apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: njila

resources:
  - ../../base

# En développement : 1 seul réplica pour économiser les ressources
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      labelSelector: "tier=microservice"
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      labelSelector: "tier=infrastructure"
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      labelSelector: "tier=gateway"

# Surcharger les ConfigMaps pour l'environnement dev
configMapGenerator:
  - name: dev-config
    namespace: njila
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
